name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt-get install -y python clang llvm llvm-dev libclang-dev libcap-dev

    - name: Build
      run: make
